import { TableActionType, TableColumn } from 'src/app/ui-kit/table/table.model';

export const correlationTableColumns: TableColumn[] = [
  { name: 'compare', content: 'index_details_id', title: 'Compare', action: TableActionType.Compare, width: 80 },
  {
    name: 'stable_index_code',
    content: 'stable_index_code',
    title: 'SIC',
    action: TableActionType.RouterLink,
    routerLink: 'index_details_id',
    width: 80,
  },
  {
    name: 'index_provider_code',
    content: 'index_provider_code',
    title: 'IPC',
    width: 120,
    pipe: 'truncate',
  },
  {
    name: 'original_currency_correlation',
    content: 'original_currency_correlation',
    title: 'Correlation',
    pipe: 'number',
    width: 120,
  },
  {
    name: 'original_currency_3y_correlation',
    content: 'original_currency_3y_correlation',
    title: '3Y Correlation',
    pipe: 'number',
    width: 120,
  },
  {
    name: 'original_currency_correlation_log_diff',
    content: 'original_currency_correlation_log_diff',
    title: 'Log Correlation',
    pipe: 'number',
    width: 120,
  },
  {
    name: 'original_currency_3y_correlation_log_diff',
    content: 'original_currency_3y_correlation_log_diff',
    title: '3Y Log Correlation',
    pipe: 'number',
    width: 120,
  },
  { name: 'num_data_points_overlap', content: 'num_data_points_overlap', title: 'Num Data Points', width: 120 },
  {
    name: 'index_provider_id_name',
    content: 'index_provider_id_name',
    title: 'Index Provider',
    width: 120,
    pipe: 'truncate',
  },
  {
    name: 'product_id_name',
    content: 'product_id_name',
    title: 'Product',
    width: 120,
  },
  {
    name: 'specification',
    content: 'specification',
    title: 'Specifications',
    pipe: 'truncate',
    width: 180,
  },
  {
    name: 'delivery_point',
    content: 'delivery_point',
    title: 'Delivery Point',
    pipe: 'truncate',
    width: 180,
  },
  {
    name: 'automatic_live_pricing_check',
    content: 'automatic_live_pricing_check',
    title: 'Automatic Live Pricing Check',
    pipe: 'boolean',
    width: 120,
  },
  {
    name: 'cfp_ready',
    content: 'cfp_ready',
    title: 'CFP Ready',
    pipe: 'boolean',
    width: 120,
  },
];
