import { TableActionType, TableColumn } from '../../../ui-kit/table/table.model';

export const permissionTableColumns: TableColumn[] = [
  { name: 'edit', content: 'id', title: 'Edit', action: TableActionType.Edit, width: 50, editOnly: true },
  { name: 'permissions_group', content: 'permissions_group', title: 'Group Name', width: 180 },
  {
    name: 'data_center_access',
    content: 'data_center_access',
    title: 'Data Center Access',
    pipe: 'boolean',
    width: 100,
  },
  {
    name: 'index_details_table',
    content: 'index_details_table',
    title: 'Index Details Permissions',
    pipe: 'permissions',
    width: 100,
  },
  { name: 'users_table', content: 'users_table', title: 'Users Permissions', pipe: 'permissions', width: 100 },
  {
    name: 'group_permissions_table',
    content: 'group_permissions_table',
    title: 'Permissions Group Permissions',
    pipe: 'permissions',
    width: 100,
  },
  {
    name: 'index_provider_table',
    content: 'index_provider_table',
    title: 'Index Providers Permissions',
    pipe: 'permissions',
    width: 100,
  },
  {
    name: 'hierarchy_table',
    content: 'hierarchy_table',
    title: 'Hierarchies Permissions',
    pipe: 'permissions',
    width: 100,
  },
  { name: 'nation_table', content: 'nation_table', title: 'Nations Permissions', pipe: 'permissions', width: 100 },
  {
    name: 'currency_table',
    content: 'currency_table',
    title: 'Currencies Permissions',
    pipe: 'permissions',
    width: 100,
  },
  { name: 'unit_table', content: 'unit_table', title: 'Units Permissions', pipe: 'permissions', width: 100 },
  {
    name: 'index_extension_data_table',
    content: 'index_extension_data_table',
    title: 'Index Extensions Permissions',
    pipe: 'permissions',
    width: 100,
  },
  {
    name: 'scrape_matching_table',
    content: 'scrape_matching_table',
    title: 'Scrape Matchings Permissions',
    pipe: 'permissions',
    width: 100,
  },
  {
    name: 'historical_data_table',
    content: 'historical_data_table',
    title: 'Historical Data Permissions',
    pipe: 'permissions',
    width: 100,
  },
  {
    name: 'can_generate_api_key',
    content: 'can_generate_api_key',
    title: 'Api Key Permissions',
    pipe: 'boolean',
    width: 100,
  },
  { name: 'data_dash_access', content: 'data_dash_access', title: 'Data Dash Access', pipe: 'boolean', width: 100 },
  { name: 'index_library', content: 'index_library', title: 'Index Library', pipe: 'permissions', width: 100 },
  { name: 'index_alerts', content: 'index_alerts', title: 'Index Alerts', pipe: 'permissions', width: 100 },
  { name: 'trading_center', content: 'trading_center', title: 'Trading Center', pipe: 'permissions', width: 100 },
  {
    name: 'derivatives_trading',
    content: 'derivatives_trading',
    title: 'Derivative Trading',
    pipe: 'permissions',
    width: 100,
  },
  { name: 'hedging_home', content: 'hedging_home', title: 'Hedging Home', pipe: 'permissions', width: 100 },
  {
    name: 'portfolio_summary',
    content: 'portfolio_summary',
    title: 'Portfolio Summary',
    pipe: 'permissions',
    width: 100,
  },
  {
    name: 'under_writer_access',
    content: 'under_writer_access',
    title: 'Underwriter Access',
    pipe: 'permissions',
    width: 100,
  },
  {
    name: 'rolling_deal_configuration',
    content: 'rolling_deal_configuration',
    title: 'Rolling Deal Configuration',
    pipe: 'permissions',
    width: 100,
  },
];
