import { TableActionType, TableColumn } from '../../ui-kit/table/table.model';

export const portfolioTableColumns: TableColumn[] = [
  {
    name: 'view_deal',
    content: 'id',
    title: 'View Deal',
    width: 80,
    action: TableActionType.Bolt,
  },
  {
    name: 'stable_index_code',
    content: 'stable_index_code',
    title: 'SIC',
    action: TableActionType.RouterLink,
    routerLink: 'index_id',
    width: 100,
  },
  { name: 'index_provider', content: 'index_provider', title: 'Index Provider', width: 100 },
  { name: 'product', content: 'product', title: 'Product', width: 120 },
  { name: 'direction', content: 'direction', title: 'Direction', width: 80, pipe: 'text-transform' },
  { name: 'style', content: 'style', title: 'Style', width: 80, pipe: 'text-transform' },
  { name: 'strike', content: 'strike', title: 'Strike', width: 100, pipe: 'number' },
  { name: 'limit', content: 'limit', title: 'Limit', width: 100, pipe: 'number' },
  {
    name: 'purchase_watch_status_time',
    content: 'purchase_watch_status_time',
    title: 'Trade Date',
    width: 120,
    pipe: 'date',
  },
  { name: 'coverage_start_in', content: 'coverage_start_in', title: 'Coverage Start', width: 120 },
  { name: 'coverage_end_in', content: 'coverage_end_in', title: 'Coverage End', width: 120 },
  { name: 'units', content: 'units_collated', title: 'Units', width: 100 },
  { name: 'desired_quantity', content: 'desired_quantity', title: 'Quantity', width: 80, pipe: 'number' },
  { name: 'premium', content: 'premium', title: 'Premium', width: 100, pipe: 'number' },
  { name: 'claims_paid', content: 'claims_paid', title: 'Claims', width: 100, pipe: 'number' },
  { name: 'bid_price', content: 'bid_price', title: 'Bid Price', width: 100, pipe: 'number' },
  { name: 'bid_expiration_time', content: 'bid_expiration_time', title: 'Bid Expiry', width: 100, pipe: 'date' },
  { name: 'bid_filled_quantity', content: 'bid_filled_quantity', title: 'Filled Quantity', width: 100, pipe: 'number' },
  {
    name: 'bid_is_partial_execution_enabled',
    content: 'bid_is_partial_execution_enabled',
    title: 'Allow Partial Execution',
    width: 100,
    pipe: 'boolean',
  },
  { name: 'status', content: 'status', title: 'Status', width: 100, pipe: 'text-transform' },
];

export const LiveTradeColumns = [
  'view_deal',
  'stable_index_code',
  'index_provider',
  'product',
  'direction',
  'style',
  'strike',
  'limit',
  'purchase_watch_status_time',
  'coverage_start_in',
  'coverage_end_in',
  'units',
  'desired_quantity',
  'premium',
  'claims_paid',
  'status',
];

export const BidColumns = [
  'view_deal',
  'stable_index_code',
  'index_provider',
  'product',
  'direction',
  'style',
  'strike',
  'limit',
  'purchase_watch_status_time',
  'coverage_start_in',
  'coverage_end_in',
  'units',
  'desired_quantity',
  'bid_price',
  'bid_expiration_time',
  'bid_filled_quantity',
  'bid_is_partial_execution_enabled',
  'status',
];

export const WatchColumns = [
  'view_deal',
  'stable_index_code',
  'index_provider',
  'product',
  'direction',
  'style',
  'strike',
  'limit',
  'purchase_watch_status_time',
  'coverage_start_in',
  'coverage_end_in',
  'units',
  'desired_quantity',
  'premium',
  'status',
];

export const StickyColumns = ['view_deal', 'stable_index_code'];
